metadata:
    appguid: 8ddf782f-708a-4578-9eda-645876e9ac0b
entity:
    name: autoscale-api
    instances: 1
    state: STARTED
    memory: 1024
    diskquota: 1024
    buildpack: java_buildpack_offline
    detectedbuildpack: java
    detectedbuildpackguid: dd470123-6a41-41a1-8f49-dfeb1561b683
    detectedbuildpackfilename: java-buildpack-offline-cflinuxfs4-v4.63.1.zip
    spacename: autoscaling
    spaceguid: afdf25df-ac17-4abf-9ac0-a37a22ac7928
    startcommand: 'JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.17.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=$TMPDIR -XX:ActiveProcessorCount=$(nproc) -Djava.ext.dirs= -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security $JAVA_OPTS" && CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.13.0_RELEASE -totMemory=$MEMORY_LIMIT -loadedClasses=25752 -poolType=metaspace -stackThreads=250 -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY && JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" && MALLOC_ARENA_MAX=2 SERVER_PORT=$PORT eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java $JAVA_OPTS -cp $PWD/.:$PWD/.java-buildpack/container_security_provider/container_security_provider-1.20.0_RELEASE.jar org.springframework.boot.loader.JarLauncher'
    environment:
        ALLOW_TRAILING_SLASHES: "false"
        API_CLIENT: autoscaling_api
        API_CLIENT_SECRET: Fdg1ydEVeKBKSzRKQa14zzk31gYrD_O2
        BROKER_HOST: https://autoscale.sys.example.com/v2
        CC_HOST: https://api.sys.example.com
        DATABASE_URL: jdbc:mysql://mysql.service.cf.internal:3306/autoscale?user=FqmvgtxfOIjMlruHGiJp&password=2isNjdd2RUmdaCeu1GKlCDcVlnYqYY&serverTimezone=UTC&useLegacyDatetimeCode=false
        DISABLE_API_CONNECTION_POOLING: "false"
        HOST_NAME: https://autoscale.sys.example.com/api/v2
        JAVA_OPTS: -Dcloudfoundry.metrics.skipSslValidation=false
        JBP_CONFIG_OPEN_JDK_JRE: '{ "jre": { version: 17.+ } }'
        JBP_CONFIG_ORACLE_JRE: '{ "jre": { version: 17.+ } }'
        JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}'
        LOG_VERBOSE: "false"
        SKIP_CERT_VERIFY: "false"
        UAA_HOST: https://login.sys.example.com
    command: ""
    healthcheck: port
    healthcheckendpoint: ""
    routes:
        - autoscale.sys.example.com
    routesurl: /v2/apps/8ddf782f-708a-4578-9eda-645876e9ac0b/routes
    stack: cflinuxfs4
    stackguid: 8e5e9961-9dea-4e32-aa9a-28123de0e212
    serviceinstances: []
    servicebindingsurl: /v2/apps/8ddf782f-708a-4578-9eda-645876e9ac0b/service_bindings
    orgguid: 1b9faba6-a7a8-42a5-9dc7-4f627d649590
    orgname: system
