metadata:
    appguid: 870519fb-69eb-45e0-a064-505b59de3bea
entity:
    name: node-app
    instances: 1
    state: STARTED
    memory: 1024
    diskquota: 1024
    buildpack: ""
    detectedbuildpack: nodejs
    detectedbuildpackguid: 017f5f72-23cb-451b-aced-e728d8e0cc83
    detectedbuildpackfilename: nodejs_buildpack-cached-cflinuxfs4-v1.8.15.zip
    spacename: sandbox
    spaceguid: f40d5887-d151-4b20-a1c3-4f93186e9505
    startcommand: npm start
    environment: {}
    command: ""
    healthcheck: port
    healthcheckendpoint: ""
    routes:
        - node-app.apps.example.com
    routesurl: /v2/apps/870519fb-69eb-45e0-a064-505b59de3bea/routes
    stack: cflinuxfs4
    stackguid: 8e5e9961-9dea-4e32-aa9a-28123de0e212
    serviceinstances: []
    servicebindingsurl: /v2/apps/870519fb-69eb-45e0-a064-505b59de3bea/service_bindings
    orgguid: 4a5cf673-7cdc-4c3b-aa4b-698811cd657e
    orgname: ds
