metadata:
    appguid: e8682924-4f03-4713-bbe6-c091068d91d3
entity:
    name: ra-java-metric
    instances: 1
    state: STARTED
    memory: 1024
    diskquota: 1024
    buildpack: ""
    detectedbuildpack: java
    spaceguid: a879dd1c-0c6d-483a-9ea0-9ca7bd8632bd
    startcommand: 'JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.17.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=$TMPDIR -XX:ActiveProcessorCount=$(nproc) -Djava.ext.dirs= -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security $JAVA_OPTS" && CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.13.0_RELEASE -totMemory=$MEMORY_LIMIT -loadedClasses=16149 -poolType=metaspace -stackThreads=250 -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY && JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" && MALLOC_ARENA_MAX=2 eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java $JAVA_OPTS -cp $PWD/.:$PWD/.java-buildpack/client_certificate_mapper/client_certificate_mapper-1.11.0_RELEASE.jar:$PWD/.java-buildpack/container_security_provider/container_security_provider-1.19.0_RELEASE.jar com.vmware.App'
    environment:
        JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { version: 17.+ } }'
    command: ""
    healthcheck: port
    healthcheckendpoint: ""
    routes:
        - ra-java-metric.apps.tas.example.io
    routesurl: /v2/apps/e8682924-4f03-4713-bbe6-c091068d91d3/routes
    stack: cflinuxfs3
    stackurl: /v2/stacks/596b9919-dd6d-4bac-a7d9-08d52c9af369
    serviceinstances: []
    serviceurl: /v2/apps/e8682924-4f03-4713-bbe6-c091068d91d3/service_bindings
