metadata:
    appguid: b16d469b-0f27-44a1-9e7e-4bcb357d8677
entity:
    name: app-usage-worker
    instances: 1
    state: STARTED
    memory: 2048
    diskquota: 1024
    buildpack: ruby_buildpack
    detectedbuildpack: ruby
    detectedbuildpackguid: f503056a-0c13-4e31-86f3-495f1ebb96a7
    detectedbuildpackfilename: ruby_buildpack-cached-cflinuxfs4-v1.10.6.zip
    spacename: system
    spaceguid: 84d46f5e-9711-4aa4-94c8-930b03be27b2
    startcommand: bin/rails server -b 0.0.0.0 -p $PORT -e $RAILS_ENV
    environment:
        ALLOW_TEST_DATA_CREATION: "false"
        ALLOW_VIEWING_LOGS: "false"
        CLOUD_CONTROLLER_URL: https://api.sys.example.com
        CUTOFF_AGE_IN_DAYS: "365"
        DATABASE_URL: mysql2://app_usage:7PvPSXXeGB9r2hSnRl7CfGVwkLiusv@mysql.service.cf.internal:3306/app_usage_service?reconnect=true
        SECRET_KEY_BASE: ck5wmCp68WHCHlxWfgsOKN0njlQkGj
        SKIP_SSL_VALIDATION: "false"
        UAA_URL: https://login.sys.example.com
        USAGE_SERVICE_UAA_CLIENT_ID: usage_service
        USAGE_SERVICE_UAA_CLIENT_SECRET: CJxP4WvqKKKqMNMb3KeRs8dQTxfOy-kd
    command: bundle exec rake worker:start
    healthcheck: process
    healthcheckendpoint: ""
    routes: []
    routesurl: /v2/apps/b16d469b-0f27-44a1-9e7e-4bcb357d8677/routes
    stack: cflinuxfs4
    stackguid: 8e5e9961-9dea-4e32-aa9a-28123de0e212
    serviceinstances:
        - name: structured-format-json
          type: user_provided_service_instance
          maintenanceinfo:
            version: ""
            description: ""
          serviceplanurl: ""
          serviceinstancekeysurl: ""
          serviceinstanceplandetails:
            name: ""
            free: false
            description: ""
            active: false
            bindbale: false
            serviceurl: ""
            label: ""
            servicebrokername: ""
    servicebindingsurl: /v2/apps/b16d469b-0f27-44a1-9e7e-4bcb357d8677/service_bindings
    orgguid: 1b9faba6-a7a8-42a5-9dc7-4f627d649590
    orgname: system
