metadata:
    appguid: 0b89a284-6ecc-4c2f-a5d1-84086762fd22
entity:
    name: p-invitations-blue
    instances: 1
    state: STOPPED
    memory: 256
    diskquota: 512
    buildpack: nodejs_buildpack
    detectedbuildpack: ""
    detectedbuildpackguid: ""
    detectedbuildpackfilename: ""
    spacename: system
    spaceguid: 84d46f5e-9711-4aa4-94c8-930b03be27b2
    startcommand: ""
    environment:
        CLOUD_CONTROLLER_URL: https://api.sys.example.com
        COMPANY_NAME: VMware RPM
        INVITATIONS_CLIENT_ID: invitations
        INVITATIONS_CLIENT_SECRET: utKebQQNAqyR84H_MYkxMFbN_e1aWnXF
        NODE_TLS_REJECT_UNAUTHORIZED: "1"
        NOTIFICATIONS_URL: https://notifications.sys.example.com
        PRODUCT_NAME: Apps Manager
        UAA_URL: https://login.sys.example.com
    command: ""
    healthcheck: port
    healthcheckendpoint: ""
    routes: []
    routesurl: /v2/apps/0b89a284-6ecc-4c2f-a5d1-84086762fd22/routes
    stack: cflinuxfs4
    stackguid: 8e5e9961-9dea-4e32-aa9a-28123de0e212
    serviceinstances: []
    servicebindingsurl: /v2/apps/0b89a284-6ecc-4c2f-a5d1-84086762fd22/service_bindings
    orgguid: 1b9faba6-a7a8-42a5-9dc7-4f627d649590
    orgname: system
